services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - 5432:5432
    container_name: postgres

  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./src:/home/node/app/src
      - ./prisma:/home/node/app/prisma
    container_name: express
    env_file:
      - .env
    depends_on:
      - db

volumes:
  postgres_data:
